name: Python package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Debug Info - Github
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Debug Info - Job
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Debug Info - Runner
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pipenv
        pipenv sync --dev
    - name: Test with unittest
      run: |
        pipenv run python -m unittest discover
    - name: Build packages
      run: |
        pipenv run python setup.py sdist
        pipenv run python setup.py bdist_wheel
    - name: Build Windows EXE
      if: runner.os == 'Windows'
      run: |
        pipenv run python setup.py build_exe

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      if: github.ref != 'refs/heads/master'
      run: docker build . --file Dockerfile --tag yawast-ci:$(date +%s)
